# https://learn.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml#specify-stages

trigger:
  paths:
    include:
    - 'pipelines/lab-1/*'

pool: default

steps:
- bash: echo "Hello world"